name: 🚀 Deploy test on push
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      #- name: Use Node.js 12.14.1
      #  uses: actions/setup-node@v2-beta
      #  with:
      #    node-version: '12.14.1'

      #- name: 🔨 Build Project
      #  run: |
      #    npm install
      #    npm run biild:test

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: vh206.timeweb.ru
          username: v3ctor_ftp
          password: XpBCc8v2
          local-dir: ./dist/
          server-dir: ./stylekit-test/
