name: 🚀 Deploy test on push
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 12.14.1
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12.14.1'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run biild:test
